//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceNeighbourPharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Medicine
    {
        public string Id { get; set; }
        public string price { get; set; }
        public string quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
