insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('benzyl alcohol', 'Zylera Pharmaceuticals, LLC', 'Construction Clean and Final Clean', 45.9, 49);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('octreotide acetate', 'Sagent Pharmaceuticals', 'Elevator', 81.34, 82);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Alcohol', 'Whip Mix Corporation', 'Fire Protection', 1.27, 41);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('DOXEPIN HYDROCHLORIDE', 'STAT Rx USA LLC', 'Structural & Misc Steel Erection', 22.95, 21);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('miconazole nitrate', 'Premier Value', 'Masonry & Precast', 68.76, 51);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Methadone Hydrochloride', 'Lake Erie Medical DBA Quality Care Products LLC', 'Framing (Wood)', 7.13, 53);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Bisacodyl', 'Physicians Total Care, Inc.', 'Roofing (Asphalt)', 12.7, 24);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Pumpkin', 'Nelco Laboratories, Inc.', 'Plumbing & Medical Gas', 51.18, 57);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('TITANIUM DIOXIDE, ZINC OXIDE', 'ATOMY CO., LTD.', 'Curb & Gutter', 76.68, 72);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('RIFAXIMIN', 'Salix Pharmaceuticals, Inc.', 'Prefabricated Aluminum Metal Canopies', 54.93, 48);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Oxygen', 'Fitzsimmons Surgical Supply, Inc', 'Construction Clean and Final Clean', 3.4, 36);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('NICOTINE', 'Novartis Consumer Health', 'Roofing (Asphalt)', 2.49, 78);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('SALICYLIC ACID', 'CVS Pharmacy', 'Rebar & Wire Mesh Install', 47.97, 96);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Peptic Relief', 'Rebel Distributors Corp', 'Prefabricated Aluminum Metal Canopies', 87.36, 39);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('TITANIUM DIOXIDE, ZINC OXIDE and OCTINOXATE', 'KANEBO COSMETICS INC.', 'Doors, Frames & Hardware', 38.95, 100);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('tizanidine', 'Apotex Corp.', 'RF Shielding', 87.95, 54);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Lisinopril', 'IVAX Pharmaceuticals, Inc.', 'Framing (Steel)', 89.93, 43);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('amiodarone hydrochloride', 'Physicians Total Care, Inc.', 'Soft Flooring and Base', 89.05, 22);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('ALCOHOL', 'American Industrial Supply, Inc.', 'Granite Surfaces', 89.14, 53);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Witch hazel', 'Walgreens', 'Epoxy Flooring', 78.53, 78);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('HYDROXYZINE PAMOATE', 'Contract Pharmacy Services-PA', 'Temp Fencing, Decorative Fencing and Gates', 95.95, 95);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Carisoprodol', 'Keltman Pharmaceuticals Inc.', 'EIFS', 34.71, 76);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('CAMPHOR (SYNTHETIC)', 'Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.', 'Asphalt Paving', 79.63, 48);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Bryonia, Ruta graveolens, Bellis perennis, Argentum metallicum,', 'Apotheca Company', 'Landscaping & Irrigation', 46.42, 100);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Anticoagulant Citrate Phosphate Dextrose (CPD) Solution and ADSOL Preservation Solution', 'Fenwal, Inc.', 'Ornamental Railings', 45.06, 25);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('clindamycin phosphate', 'Pharmacia and Upjohn Company', 'Structural & Misc Steel Erection', 54.31, 38);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('MUCOR PLUMBEUS', 'ALK-Abello, Inc.', 'Epoxy Flooring', 5.6, 72);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Amlodipine Besylate and Benazepril HCL', 'American Health Packaging', 'Framing (Steel)', 35.2, 74);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('OCTINOXATE, TITANIUM DIOXIDE', 'Parfums Christian Dior', 'HVAC', 2.62, 71);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Alfuzosin Hydrochloride', 'Wockhardt USA LLC.', 'Painting & Vinyl Wall Covering', 91.94, 63);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('glimepiride', 'Cardinal Health', 'RF Shielding', 39.18, 30);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('conjugated estrogens and medroxyprogesterone acetate', 'Dispensing Solutions, Inc.', 'Exterior Signage', 81.24, 87);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Zinc Gluconate', 'ProPhase Labs, Inc.', 'Hard Tile & Stone', 84.88, 92);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('POLYETHYLENE GLYCOL 400', 'HANLIM PHARM. CO., LTD.', 'Curb & Gutter', 53.62, 48);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Rocky Mountain Juniper', 'Nelco Laboratories, Inc.', 'Glass & Glazing', 68.59, 44);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Camphor (Natural)', 'Chongqing Yilin Science and Technology Co., Ltd.', 'HVAC', 23.23, 33);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Desmopressin Acetate', 'Sun Pharmaceutical Industries Limited', 'Painting & Vinyl Wall Covering', 97.04, 90);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('bisoprolol fumarate', 'Mylan Pharmaceuticals Inc.', 'Drywall & Acoustical (MOB)', 22.62, 98);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Tobramycin and Dexamethasone', 'Bausch & Lomb Incorporated', 'Masonry', 98.85, 77);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Boricum gluconicum, Calcarea gluconica, Chromium gluconicum, Cobaltum gluconicum, Ferrum fluconicum, Kali gluconicum, Magnesia gluconica,', 'Deseret Biologicals, Inc.', 'Roofing (Asphalt)', 84.43, 49);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('pioglitazone hydrochloride', 'American Health Packaging', 'Ornamental Railings', 64.35, 30);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('milnacipran hydrochloride', 'Forest Laboratories, Inc.', 'Exterior Signage', 41.03, 75);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('SALICYLIC ACID', 'CEN BEAUTY LLC', 'Ornamental Railings', 55.16, 33);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Plantar Wart Removers', 'Premier Brands of America Inc.', 'Framing (Steel)', 16.69, 92);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Treatment Set TS330316', 'Antigen Laboratories, Inc.', 'Electrical', 89.39, 37);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('butalbital, acetaminophen and caffeine', 'Preferred Pharmaceuticals, Inc.', 'Electrical and Fire Alarm', 91.0, 82);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Valacyclovir Hydrochloride', 'Physicians Total Care, Inc.', 'Granite Surfaces', 63.78, 87);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('FUSARIUM VASINFECTUM', 'ALK-Abello, Inc.', 'Retaining Wall and Brick Pavers', 50.18, 85);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Sodium Fluoride and Potassium Nitrate', 'Tom''s of Maine, Inc.', 'Wall Protection', 54.53, 43);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Salicylic Acid', 'Aidance Skincare & Topical Solutions, LLC', 'Plumbing & Medical Gas', 68.83, 71);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Codeine Phosphate, Guaifenesin, Pseudoephedrine Hydrochloride', 'Sallus Laboratories, LLC', 'EIFS', 21.45, 44);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Acetaminophen, Diphenhydramine HCl', 'Wakefern Food Corporation', 'Drilled Shafts', 12.35, 46);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Amlodipine Besylate', 'Cadila Healthcare Limited', 'Masonry & Precast', 4.18, 93);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('estradiol valerate', 'Par Pharmaceutical Inc.', 'Prefabricated Aluminum Metal Canopies', 72.55, 100);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('COPPER', 'REMEDY MAKERS', 'Framing (Wood)', 52.51, 49);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Olanzapine', 'Dispensing Solutions, Inc.', 'Masonry & Precast', 32.35, 58);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Alcohol', 'Mada Medical Products, Inc.', 'Sitework & Site Utilities', 20.85, 45);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Robinul', 'West-ward Pharmaceutical Corp.', 'Glass & Glazing', 26.97, 70);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('ciprofloxacin', 'HHS/Program Support Center/Supply Service Center', 'Painting & Vinyl Wall Covering', 65.91, 89);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Potassium Chloride and Dextrose Monohydrate', 'Baxter Healthcare Corporation', 'Ornamental Railings', 90.03, 28);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Oxygen', 'Family Medical Supply Inc.', 'Drywall & Acoustical (FED)', 19.94, 28);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Titanium Dioxide, Zinc Oxide', 'Have and Be Co., Ltd.', 'Drywall & Acoustical (FED)', 11.79, 75);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Octinoxate, Octisalate', 'The Mentholatum Company', 'Termite Control', 16.1, 54);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Ranitidine Hydrochloride', 'SAFEWAY INC.', 'Electrical', 45.6, 88);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Triclosan', 'SJ Creations, Inc.', 'Fire Protection', 35.36, 77);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Ampicillin sodium', 'Claris Lifesciences, Inc.', 'RF Shielding', 52.43, 94);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Amino acids, Apis mellifica, Biotin, Epidermis, Galium aparine, Hamamelis virginiana, Hepar suis, HGH, Natrum muriaticum,', 'Liddell Labroatories', 'Temp Fencing, Decorative Fencing and Gates', 14.34, 48);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Fluorouracil', 'Pfizer Laboratories Div Pfizer Inc.', 'Retaining Wall and Brick Pavers', 28.55, 40);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Norethindrone Acetate and Ethinyl Estradiol', 'Actavis Pharma, Inc.', 'Plumbing & Medical Gas', 4.59, 26);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Acetaminophen, Dextromethorphan HBr, Doxylamine succinate', 'Kareway Product, Inc.', 'Rebar & Wire Mesh Install', 74.23, 82);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Mirtazapine', 'Actavis Pharma, Inc.', 'HVAC', 8.15, 25);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE', 'NATURE REPUBLIC CO., LTD.', 'Exterior Signage', 33.58, 67);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Olanzapine', 'Dispensing Solutions, Inc.', 'Hard Tile & Stone', 31.76, 89);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Arnica Aurum 20/30', 'Uriel Pharmacy Inc.', 'Electrical and Fire Alarm', 66.69, 24);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Amantadine Hydrochloride', 'Hi-Tech Pharmacal Co., Inc.', 'Granite Surfaces', 94.85, 40);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('PETROLATUM and LANOLIN', 'RiteAid', 'Retaining Wall and Brick Pavers', 87.44, 28);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Carbon Dioxide-Oxygen Mixture', 'Roberts Oxygen Company, Inc.', 'Elevator', 44.22, 72);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Benzonatate', 'Rebel Distributors Corp', 'Masonry', 42.8, 20);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Miconazole Nitrate', 'PSS World Medical, Inc.', 'Drywall & Acoustical (FED)', 7.32, 49);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Lamotrigine', 'NCS HealthCare of KY, Inc dba Vangard Labs', 'Soft Flooring and Base', 86.98, 37);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Naproxen Sodium', 'Wal-Mart Stores Inc', 'Masonry', 7.66, 71);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('TITANIUM DIOXIDE and ZINC OXIDE', 'Levlad, LLC', 'Structural and Misc Steel (Fabrication)', 14.76, 69);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Amoxicillin and Clavulanate Potassium', 'Teva Pharmaceuticals USA Inc', 'Termite Control', 76.42, 33);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('SODIUM SULFATE', 'Washington Homeopathic Products', 'Roofing (Asphalt)', 57.24, 52);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Oxygen', 'Ambercare Medical Supply Co.', 'Construction Clean and Final Clean', 74.73, 77);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('doxycycline', 'Mylan Pharmaceuticals Inc.', 'Painting & Vinyl Wall Covering', 20.84, 35);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('WITCH HAZEL', 'Dr. Dream Inc', 'Landscaping & Irrigation', 87.57, 92);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Benzocaine', 'HEB', 'EIFS', 96.73, 75);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Isopropyl Alcohol', 'Jiangsu Province JianErKang Medical Dressing Co. ,Ltd.', 'Landscaping & Irrigation', 50.7, 62);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Nicardipine Hydrochloride', 'Epic Pharma, LLC', 'Marlite Panels (FED)', 42.74, 58);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('ibuprofen', 'Walgreen Company', 'Casework', 89.5, 28);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('PICEA MARIANA RESIN, ACTIVATED CHARCOAL, STRYCHNOS NUX-VOMICA SEED, ROBINIA PSEUDOACACIA BARK', 'Laboratoires Boiron', 'EIFS', 72.46, 29);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Benzalkonium Chloride', 'Jets, Sets, & Elephants Beauty Corp.', 'Roofing (Metal)', 30.14, 67);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Glipizide and Metformin HCl', 'REMEDYREPACK INC.', 'Soft Flooring and Base', 94.47, 49);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Undecylenic Acid', 'Efficient Laboratories Inc', 'Structural & Misc Steel Erection', 80.15, 84);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Alprazolam', 'Major Pharmaceuticals', 'RF Shielding', 97.99, 94);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 'MSD Consumer Care, Inc.', 'Masonry & Precast', 3.52, 62);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('amlodipine and atorvastatin', 'Mylan Pharmaceuticals Inc.', 'Asphalt Paving', 42.79, 31);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Tramadol Hydrochloride Tablets', 'Accord Healthcare, Inc.', 'Electrical', 51.63, 72);
insert into Medicines (Name, Description, Category, Price, NumberOfStock) values ('Glimepiride', 'Aidarex Pharmaceuticals LLC', 'Temp Fencing, Decorative Fencing and Gates', 18.79, 26);
